services:

  db:
    image: mariadb
    container_name: mydb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/mysql

  app:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "sleep 15 && node server.js"

volumes:
  mydata:
